package model.generico;

public enum TipoToken {
    PAREN_ESQ, PAREN_DIR,
    CHAVE_ESQ, CHAVE_DIR,
    VIRGULA, PONTO, MENOS, MAIS, PONTO_VIRG, BARRRA, ASTERISCO,

    EXCLAMACAO, EXCLAMACAO_IGUAL,
    IGUAL, IGUAL_IGUAL,
    MAIOR, MAIOR_IGUAL,
    MENOR, MENOR_IGUAL,

    IDENTIFICADOR,
    STRING,
    NUMERO,

    E, OU,
    SE, SENAO,
    FUNCAO,
    FALSO, VERDADEIRO,
    PARA, ENQUANTO,
    IMPRIMIR, RETORNAR,
    VAR,
    NULO,

    FIM_DO_ARQUIVO
}
